version: "3.0"

services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
    - './data:/data/db'

  mongo-express:
    image: mongo-express
    ports:
      - "8888:8081"
    depends_on:
      - mongo
    links:
      - mongo
    restart: always
